### ISSUE TITLE
Repeated webpack searches

### ISSUE THREAD

**Issue by rauenzi** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#1]
Here you search all of webpack modules for a module to use https://github.com/RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK/blob/main/src/AutoIdleOnAFK/index.js#L193

But really the module itself should be found once and stored in a local variable. I am still approving this for BD since this only runs on blur or focus rather than constantly.

**Comment by RoguedBear** [comment]
Thank you for accepting my submission!
I'll implement your suggestion to find and store the webpack modules once in the next update
