### ISSUE TITLE
Less time option for to go back to idle.

### ISSUE THREAD

**Issue by BigFlubba** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#17]
I would like the option for the idle time to go lower then 5 minutes. I was thinking of more down to 1 minute as the least.

**Comment by RoguedBear** [comment]
duplicate of #2.
My reasoning of minimum timeout being 5 minutes is the way I see it, having a pretty low timeout doesn't make sense in terms of user being "idle" or "afk". Just switching windows between discord and some other app for a while could be interpreted as being afk when it is not.

However, if you still insist on having a low timeout you can manually override that minimum timeout by editing the config file whose steps I've written in my comment on #2 over [here](https://github.com/RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK/issues/2#issuecomment-1024280678)
