### ISSUE TITLE
Allow to set the "Idle" Mode to something else

### ISSUE THREAD

**Issue by LeonGamer1707** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#18]
Add an option to change the "Idle" Mode to a status or something else like "Do not disturb" or "offline"

**Comment by RoguedBear** [comment]
can you elaborate more on your issue?
from what i understand, you want when the plugin goes to idle mode or sets your status to "Idle" you want that "Idle" to be some other status like "DnD" or "Invisible". 

If that is what you're asking then that functionality is already provided by the plugin and you can configure it in the plugin's settings page

**Comment by LeonGamer1707** [comment]
Wait, the plugin had a settings page? How did i miss that?
In that case you can ignore this issue.
