### ISSUE TITLE
AutoIdleOnAFK Could not be constructed

### ISSUE THREAD

**Issue by Joenator** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#22]
AutoIdleOnAFK: Could not be constructed.
    at Object.initializeAddon (<anonymous>:4:306851)
    at Object.loadAddon (<anonymous>:4:268341)
    at Object.loadAddon (<anonymous>:4:305889)
    at FSWatcher.<anonymous> (<anonymous>:4:266190)
    
Happened after what I assume is a new Discord/BD update. Reinstalling BD did not fix.

**Comment by IXSENPA1XI** [comment]
same here

**Comment by RoguedBear** [comment]
i have the issue on my side as well. Will push a fix by today

**Comment by RoguedBear** [comment]
the construction error is resolved in commit 0cc9d7de2f13787c97ea62831bf3c19808268466, but discord changed the way user settings (like status) are changed, so the plugin cant change status from online to idle right now.

It might take me a while to figure out how to get that part working

**Comment by RoguedBear** [comment]
to use the fixed version you need to redownload the plugin, since BetterDiscord does not show update banners for construction errors.
you can either wait for BD plugin site to approve the update there or download from this repo
