### ISSUE TITLE
[NOTICE] Redownload if you're facing construction/compile error

### ISSUE THREAD

**Issue by RoguedBear** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#26]
A recent discord update broke the plugin resulting in construction error. 
Plugin version `v0.3.1` fixed it, but for plugins that have construction error, BetterDiscord does not show an update banner. You need to redownload the plugin again.

You can download from:
- [BetterDiscord's website](https://betterdiscord.app/plugin/AutoIdleOnAFK) ~~(**after** the v0.3.1 update is approved, as of now it shows the `v0.3.0` version)~~ as of 12/08/22 `v0.3.1` update has been approved and is shown on BD site
- [This repo](https://github.com/RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK/tree/v0.3.1/release)

**Comment by Austinkid20** [comment]
Downloaded the new version, works perfectly
