### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Lagomorpheus** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#39]
is this plugin compatible with dnd while playing plugin? if the other plugin changes status to dnd will this one overlap it and change it to idle 5 minutes after? I want to use both but don't want it to change me from dnd to idle.

**Comment by RoguedBear** [comment]
yes. The plugin keeps track if the status has been changed by the plugin or not and stores it's value in the config.
if say your AFK status is dnd and AutoIdleOnAFK changes the status, the value `IdleSetByPlugin` will be true.
But if you, or DndWhilePlaying changes the status to dnd, `IdleSetByPlugin` will be false and the plugin would not activate again until you or another plugin set the status is back to online

I hope this answered your query
