### ISSUE TITLE
Sliders for timeout settings appear as volume icons, can't be edited

### ISSUE THREAD

**Issue by SabreCat** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#41]
Just installed this plugin today. Opening up the settings, I see the following:

![image](https://user-images.githubusercontent.com/4501321/226761097-1a4485a8-75e5-4186-85b8-4845fa883741.png)

Note the strange little black volume icons. Mousing over one produces this thermometer-style slider:

![image](https://user-images.githubusercontent.com/4501321/226761189-9e853317-25ed-41e5-affc-dbf4ce54d6d0.png)

But no matter what I do, I can't actually see what the timeout is set to or adjust it to anything new.

**Comment by RoguedBear** [comment]
this is issue will automatically resolve when BDPluginLibrary fixes it. I see a pull request is open there to fix this issue here: https://github.com/rauenzi/BDPluginLibrary/pull/184

in the next update of BDPluginLibrary the sliders will come back
