### ISSUE TITLE
[REQUEST] AutoIdleAFK

### ISSUE THREAD

**Issue by Lagomorpheus** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#42]
Do you think you could add an option to auto DND while playing a game + ability to whitelist certain games? QWERT does not appear to be updating the plugin that does this or has retired it, I have ADHD and prefer DND while playing as it helps me get immersed and less distracted.

**Comment by RoguedBear** [comment]
hmm, I understand that DNDWhilePlaying hasn't been updated in a long while. I can certainly look into adding that functionality into this plugin, or I can open a pull request in QWERTxD's repository to fix DNDWhilePlaying, 

I won't be able to give an ETA, but i'll definitely look into adding this feature/fixing their plugin whenever i get the time.

**Comment by Lagomorpheus** [comment]
Coming back to this because of a discord update, for DnDWhilePlaying, discord added a way to disable detection for individual apps, however it still sets DnD even though an app is set to not show up in status, can you include a way in the plugin to whitelist the apps that are set to hidden?

**Comment by RoguedBear** [comment]
hmm, I am not that familiar with BetterDiscord's API to know how would i implement that, but i can give it a try. 
Although this time I can not promise or give any ETA when i would work on that, i'm busy on my internship for the majority of my week leaving me with little free time to work on my hobby projects

**Comment by RoguedBear** [comment]
closing as https://github.com/QWERTxD/BetterDiscordPlugins/pull/369 is merged
