### ISSUE TITLE
afk on vc

### ISSUE THREAD

**Issue by valzwrld** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#43]
could u make it where it still works if ur in a private dm or something?

**Comment by RoguedBear** [comment]
On 21 April 2023 00:34:22 GMT+05:30, valzwrld ***@***.***> wrote:
>could u make it where it still works if ur in a private dm or something?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK/issues/43
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>
you'd have to elaborate on your request a little more, I don't understand what exactly is your request. do you want to dnd yourself when you're in a VC?

**Comment by valzwrld** [comment]
id like it to make my status idle when im not on disc for however long i set it to if im on a vc. because right now if ur on a vc it doesnt work

**Comment by RoguedBear** [comment]
well yes, i could introduce a setting to ignore vc state when deciding afk condition

**Comment by valzwrld** [comment]
thank you it would be really helpful for me

**Comment by RoguedBear** [comment]
i have added this setting in the new update. BetterDiscord should prompt you to update the plugin in a few days or you can directly download from this repo

**Comment by valzwrld** [comment]
thank you but how exactly do i turn it on i dont see it on the settings

**Comment by RoguedBear** [comment]
after you have updated the plugin to `v0.4.0`, you'll see an option in the settings like in this screenshot

![image](https://github.com/RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK/assets/39442192/0aaa70eb-26ad-47b6-b917-1a2fdb79c86f)

**Comment by valzwrld** [comment]
[image: image.png]
IM ON the new version and it still does not work
[image: image.png]

**Comment by RoguedBear** [comment]
ah yes, i forgot to mention I manually updated ZeresPluginLibrary as well. switches \ toggle were broken 4 days back which was fixed on Saturday. 
might take a while for BD to prompt you for that as well.
