### ISSUE TITLE
Crash discord when changed from afk to online

### ISSUE THREAD

**Issue by Kieaer** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#44]
![image](https://user-images.githubusercontent.com/44261958/235625687-6adf9936-371b-4549-8bbd-2d55169da390.png)

There're no errors logged to ``debug.log``.

**Comment by RoguedBear** [comment]
i have not been able to reproduce a crash on my side, the plugin has been working well.

can you elaborate what steps and settings lead you to a crash?

**Comment by Kieaer** [comment]
Turn on Always Revert To Online and wait 5 minute to set idle
and back to online to crash discord

**Comment by Kieaer** [comment]
This bug seems to have been fixed by BetterDiscord's update 2 days ago.
