### ISSUE TITLE
Plugin doesn't revert status to online automatically

### ISSUE THREAD

**Issue by TheSnorlaxBoi** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#53]
So, I don'ty know if it's because one of Discord & BD's update broke something, but the plugin doesn't revert the chosen status (Idle, Invisible or DND) to online as it's supposed to do. 

It does go from Online to the chosen status though.

I don't know if it's just me or if others are impacted but regardless, I'm merely pointing it out.

**Comment by TheSnorlaxBoi** [comment]
EDIT : My bad, I tried tinkering with it and it's working once more. Sorry for the bother

**Comment by RoguedBear** [comment]
its alright. would you mind sharing what happened?
