### ISSUE TITLE
Multiple Device Support

### ISSUE THREAD

**Issue by bobbyl140** [RoguedBear/BetterDiscordPlugin-AutoIdleOnAFK#6]
This plugin is great, however I think it could be improved to support multiple devices. If I install on two devices, go idle on one for longer than the timeout, and become active on the other, it doesn't change to online because the idle status came from the forst device. If there could be an option for "Always Un-AFK" I would be more interested.

**Comment by RoguedBear** [comment]
Having multi device support would be based on these 2 assumptions first of all:
- both devices have BetterDiscord
- both devices have this plugin running

but based on current implementation, if you go AFK from device 1 and your status changes to idle but then come back online on device 2, the plugin on device 2 would detect that the status is idle (or whatever afk status you have set) but was not changed by plugin on device 2 so it'll leave it as it is. If you go back to device 1 then your AFK would be removed.

To have both the plugin installations synced, the data stored by plugins would need to be stored somewhere remote which both plugins can access. Like how discord stores your settings (like current status, bio etc) on their servers. 

Theoretically there could be 2 ways to achieve that: 
1) either by storing plugin data on discord servers which I believe is not a possibility for BetterDiscord plugins. 
2) or by utilising some 3rd party service like Github Gists or pastebin, but as far as I know it could go against BetterDiscord's plugin policy though i may have to check on that. Even if it wasn't, then users would have to provide their Gist/pastebin URLs and authorisation tokens.

2nd option could be a limitation for me if I want to keep my plugin on BD website published and a hassle for other users, but if you have some coding experience and want to spend the time developing multi device support, then you can create a fork of this repo and create your own version of the plugin implementing the 2nd option. 

I won't be implementing this feature for the time being, but if I learn in the future method 1 is possible, I would look into implementing this request.

**Comment by bobbyl140** [comment]
Thank you for the detailed response. What you said makes sense, however, instead of requiring the clients to sync data, could there be an option to change from idle to online no matter what, even if the idle status didn’t originate from that client? If you still would rather not implement this I understand. Thanks!

**Comment by RoguedBear** [comment]
i could add one option "keep track of status changes made by plugin" which when turning off would fall back to the behavior you describe.
though adding that would take time.

**Comment by bobbyl140** [comment]
If I get some time today I’ll see if I can implement it. Thank you again.

**Comment by RoguedBear** [comment]
completed in #7 & #9

**Comment by nearcatch** [comment]
FYI, just reading this: I wonder if you couldn't sync it across clients by changing the user's status message with an invisible character, like the [zero-width space](https://en.wikipedia.org/wiki/Zero-width_space). If you append this to the user's status message whenever AFK is activated, then the plugin could put the user back online whenever it detects that character (and remove the invisible character), because the assumption will be that the plugin on another computer changed the user's status.

**Comment by BigFlubba** [comment]
Would be more work but I would think the about me would be a more feasible option. One other way is how they do usrbg and try that route with alm the accounts and the plugins hook into a master like with everyone's ID's and status and data needed for it to work.

**Comment by nearcatch** [comment]
> Would be more work but I would think the about me would be a more feasible option. One other way is how they do usrbg and try that route with alm the accounts and the plugins hook into a master like with everyone's ID's and status and data needed for it to work.

About Me might be better since adding a zero-width space to status message might create a blank status if none already exists. But wherever it's added, I think it's an option to sync the AFK status across computers without using a separate server.

**Comment by bobbyl140** [comment]
It does sound good, but what are the chances discord either catches on, or simply disallows these kinds of characters in bios?

**Comment by RoguedBear** [comment]
> It does sound good, but what are the chances discord either catches on, or simply disallows these kinds of characters in bios?

now that you bring this up, it does remind me that I read in the BD server that certain APIs are expected to be used more, some are not, so "automating" the latter ones could have your account flagged.

Like changing your user status many times a day is okay but changing your about me/bio frequently could be sus at best.

so i guess current solution is sufficient for the time being.
